#pragma once

#define FRC_VERSION_MAJOR 2
#define FRC_VERSION_MINOR 1

#define FRC_STR_HELPER(x) #x
#define FRC_STR(x) FRC_STR_HELPER(x)
#define FRC_VERSION_STRING FRC_STR(FRC_VERSION_MAJOR) "." FRC_STR(FRC_VERSION_MINOR)
